### ISSUE TITLE
Bullseye is unusable on qemu-ed arm64 currently

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [moby/qemu#19]
Qemu core dumps in a number of occasions.

Below is a simple example installing `libc-bin`.

This is working fine with debian buster, so, something with bullseye (linkage?) is triggering (more of) these issues.

This happens in Docker for mac 3.3.3, and also on a linux host.

It seems this project (moby/qemu) is way behind upstream. Is there still a strong reason to rely on this fork? 

```
docker run -ti docker.io/library/debian:bullseye-slim@sha256:9f8ab8961b279bcad1a1711fff7e65d1a579845fe57b8605798394f23fe8e902 bash

apt install libc-bin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Recommended packages:
  manpages
The following packages will be upgraded:
  libc-bin
1 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Need to get 742 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main arm64 libc-bin arm64 2.31-12 [742 kB]
Fetched 742 kB in 1s (792 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 6953 files and directories currently installed.)
Preparing to unpack .../libc-bin_2.31-12_arm64.deb ...
Unpacking libc-bin (2.31-12) over (2.31-11) ...
Setting up libc-bin (2.31-12) ...
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
dpkg: error processing package libc-bin (--configure):
 installed libc-bin package post-installation script subprocess returned error exit status 139
Errors were encountered while processing:
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Doing some test with latest upstream qemu (for a buildkit image).

**Comment by tonistiigi** [comment]
The shown command seems to work fine with [current](https://github.com/tonistiigi/binfmt/releases/tag/deploy%2Fv6.1.0-21) qemu images so closing. Reopen with repro instructions if you still see it.

**Comment by MrXhh** [comment]
This fix my problem 👍 :+1 if this working for you.
`docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes`

https://github.com/docker/buildx/issues/1170#issuecomment-1159350550
