### ISSUE TITLE
Error while building/running Java application on Docker Mac for ARM64

### ISSUE THREAD

**Issue by stephen-turner** [moby/qemu#2]
See docker/for-mac#3646 for details. Reported against Docker Desktop but the bug is probably in the qemu code.

**Comment by tuonga** [comment]
I worked with the original reporter of issue to test QEMU 4.0.0 and it fixed his problem.  We can expect the next version of Docker Desktop Edge to fix this problem.  Closing for now.

**Comment by leshik** [comment]
@tuonga Is the fix present in Docker Desktop for Mac `2.1.0.0 (36874)`?
I have a (not quite) similar issue but I'm not sure if it was already fixed or not.

**Comment by tuonga** [comment]
> @tuonga Is the fix present in Docker Desktop for Mac `2.1.0.0 (36874)`?
> I have a (not quite) similar issue but I'm not sure if it was already fixed or not.

Yes it should be in 36874.  Can you create a new ticket describing the problem, including steps to reproduce if possible?  Thanks!
